site_name: Spreadneck's Wiki
use_directory_urls: true
nav:
  - index.md
  - Homelab:
    - homelab/index.md
  - About:
    - about/index.md
    - This Site: about/this_site.md
  - Blog: 
    - blog/index.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - blog:
      blog_dir: blog
      blog_index_title: "Blog"
      blog_toc: false
      post_date_format: full
  - tags
  - search
  - meta
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      exclude:
        - README.md
        - index.md
  - git-committers:
      repository: spreadneck/wiki
      branch: main
      exclude:
        - README.md
        - index.md
  - callouts
  - git-authors:
      show_email_address: false
      exclude:
        - README.md
        - index.md
  - mike
markdown_extensions:
  - attr_list
  - md_in_html
  # Pyhton Markdown
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - nl2br
  - admonition
repo_url: https://github.com/spreadneck/wiki
repo_name: spreadneck/wiki
extra:
  version:
    provider: mike
  generator: false
